name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error  # Падать только на errors, warnings разрешены
          output-file: hadolint-report.txt

      - name: Upload Hadolint report
        uses: actions/upload-artifact@v4
        if: always()  # Загружать артефакт даже если предыдущий шаг упал
        with:
          name: hadolint-report
          path: hadolint-report.txt

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Check out repository code
        uses: actions/checkout@v4

      # Шаг 2: Собрать Docker образ
      - name: Build Docker image
        run: |
          docker build -t myapp:test -f Laba_1/Dockerfile .
          echo "Docker image built successfully!"

      # Шаг 3: Проверить, что контейнер запускается
      - name: Test container
        run: |
          docker run --rm myapp:test echo "Container works!"

      -name: Save build log
      run: |
        echo "Build completed at $(date)" > build-log.txt
        docker images | grep myapp >> build-log.txt

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build-log.txt

