name: CI Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Job 1: Проверка качества Dockerfile
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Laba_1/Dockerfile
          failure-threshold: error  # Падать только на errors, warnings разрешены
          output-file: hadolint-report.txt

      - name: Upload Hadolint report
        uses: actions/upload-artifact@v4
        if: always()  # Загружать артефакт даже если предыдущий шаг упал
        with:
          name: hadolint-report
          path: hadolint-report.txt

  # Job 2: Сборка (запускается только после успешного lint)
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myapp:test -f Laba_1/Dockerfile .
          echo "Docker image built successfully!"

      - name: Test container
        run: |
          docker run --rm myapp:test echo "Container works!"

      - name: Save build log
        run: |
          echo "Build completed at $(date)" > build-log.txt
          docker images | grep myapp >> build-log.txt

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build-log.txt
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Laba_1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

