name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Check out repository code
        uses: actions/checkout@v4

      # Шаг 2: Собрать Docker образ
      - name: Build Docker image
        run: |
          docker build -t Laba_1:test .
          echo "Docker image built successfully!"

      # Шаг 3: Проверить, что контейнер запускается
      - name: Test container
        run: |
          docker run --rm Laba_1:test echo "Container works!"
